# Generated by Django 5.2.4 on 2025-07-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_book_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
