# Generated by Django 5.2.4 on 2025-08-02 09:15

from django.db import migrations


TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION notify_booking_change()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM pg_notify(
        'booking_channel',
        json_build_object(
            'table', TG_TABLE_NAME,
            'op',    TG_OP,
            'data',  row_to_json(NEW)
        )::text
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_booking_notify ON app_book;

CREATE TRIGGER trg_booking_notify
AFTER INSERT ON app_book
FOR EACH ROW EXECUTE FUNCTION notify_booking_change();
"""

REVERSE_SQL = """
DROP TRIGGER IF EXISTS trg_booking_notify ON app_book;
DROP FUNCTION IF EXISTS notify_booking_change();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_book_email_book_comments_alter_book_date'),
    ]

    operations = [
        migrations.RunSQL(
            TRIGGER_SQL,
            reverse_sql=REVERSE_SQL
        )
    ]
